name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build all and examples
        run: |
          make -k
          ./test
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build all and examples
        run: |
          make -k
          ./test
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build all and examples
        run: |
          make -k
          ./test
        env:
          CC: clang
          CXX: clang++
# TODO: there is not build for Windows
